### ISSUE TITLE
初始化客户端失败: 超时

### ISSUE THREAD

**Issue by wangxixi789** [krau/SaveAny-Bot#29]
![Image](https://github.com/user-attachments/assets/4985f03f-bd32-41ba-8a49-8a95f15f7755)
如图所示socks在pc端没问题
这是docker端的配置
![Image](https://github.com/user-attachments/assets/939cee11-f954-40f0-9642-c8ecba55ae47)
启动容器后报错如下：

![Image](https://github.com/user-attachments/assets/f6d6ad8c-2b2b-47e9-a542-da34d9ad76f5)

**Comment by wangxixi789** [comment]
配置都是默认的，只更改了下载目录，以及机器人bot的api

**Comment by krau** [comment]
docker 不能直接访问宿主机网络, 如果你不熟悉其用法, 请将容器设为 host 模式:

修改 docker-compose.yml , 添加 `network_mode: host` 

```yml
services:
  saveany-bot:
    image: ghcr.io/krau/saveany-bot:latest
    container_name: saveany-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml
      - ./downloads:/app/downloads
      - ./cache:/app/cache
    network_mode: host
```
