### ISSUE TITLE
使用二进制文件部署无法更新

### ISSUE THREAD

**Issue by Arturia169** [krau/SaveAny-Bot#84]
### 👾 问题描述

root@Ryan:~/saveany-bot# ./saveany-bot upgrade
Binary update failed: Get "https://api.github.com/repos/krau/SaveAny-Bot/releases": dial tcp 199.59.148.9:443: connect: connection refused

### 📄 配置文件

```toml
#创建文件时，若需要保留中文注释，请务必确保本文件编码为 UTF-8 ，否则会无法读取。
workers = 4 # 同时下载文件数
retry = 3   # 下载失败重试次数
threads = 4 # 单个任务下载最大线程数
stream = false # 使用stream模式, 详情请查看文档

[telegram]
# Bot Token
# 更换 Bot Token 后请删除数据库文件和 session.db
token = ""
# Telegram API 配置, 若不配置也可运行, 将使用默认的 API ID 和 API HASH
# 推荐使用自己的 API ID 和 API HASH (https://my.telegram.org)
# app_id = 
# app_hash = ""

[telegram.proxy]
# 启用代理连接 telegram, 只支持 socks5
enable = true
url = "socks5://127.0.0.1:7890"


# 存储配置列表
[[storages]]
# 标识名, 需要唯一
name = "本地硬盘-音频类"
# 存储类型, 目前可用: local, alist, webdav, minio
type = "local"
# 启用存储
enable = true
# 文件保存根路径
base_path = "/mnt/sdb1/TGDown/音频类"

[[storages]]
name = "本地硬盘-视频类"
type = "local"
enable = true
base_path = "/mnt/sdb1/TGDown/视频类"

[[storages]]
# 标识名, 需要唯一
name = "本地硬盘-图片类"
# 存储类型, 目前可用: local, alist, webdav, minio
type = "local"
# 启用存储
enable = true
# 文件保存根路径
base_path = "/mnt/sdb1/TGDown/图片类"

[[storages]]
name = "Alist-音频类"
type = "alist"
enable = false  #记得启用
base_path = '/J1800/TGDown/音频类'
url = 'http://192.168.5.5:5244'
username = 'admin'
password = 'admin169'
token_exp = 86400  # 86400--1天   604800--7天   1296000--15天   2592000--30天   15552000--180天
# alist 可直接使用 token 登录, 此时 username, password, token_exp 将被忽略
# 请自行在 alist 侧配置合理的 token 过期时间
# token = ""

[[storages]]
name = "Alist-视频类"
type = "alist"
enable = false  #记得启用
base_path = '/J1800/TGDown/视频类'
url = 'http://192.168.5.5:5244'
username = 'admin'
password = 'admin169'
token_exp = 86400  # 86400--1天   604800--7天   1296000--15天   2592000--30天   15552000--180天
# alist 可直接使用 token 登录, 此时 username, password, token_exp 将被忽略
# 请自行在 alist 侧配置合理的 token 过期时间
# token = ""

[[storages]]
name = "Alist-图片类"
type = "alist"
enable = false  #记得启用
base_path = '/J1800/TGDown/图片类'
url = 'http://192.168.5.5:5244'
username = 'admin'
password = 'admin169'
token_exp = 86400  # 86400--1天   604800--7天   1296000--15天   2592000--30天   15552000--180天
# alist 可直接使用 token 登录, 此时 username, password, token_exp 将被忽略
# 请自行在 alist 侧配置合理的 token 过期时间
# token = ""

[[storages]]
name = "MyWebdav"
type = "webdav"
enable = false
base_path = '/path/telegram'
url = 'https://example.com/dav'
username = 'username'
password = 'password'

[[storages]]
name = "MyMinio"
type = "minio"
enable = false
endpoint = 'play.min.io'
use_ssl = true
access_key_id = ''
secret_access_key = ''
bucket_name = 'saveanybot'
base_path = '/path/telegram'

# 用户列表
[[users]]
# telegram user id
id = 
# 开启黑名单，开启后下方留空以使用所有存储，反之则为白名单，白名单请在下方输入允许的存储名
blacklist = true
# 将列表留空并开启黑名单模式以允许使用所有存储，此处示例为黑名单模式，用户114514 可使用所有存储
storages = []


[[users]]
id = 123456
blacklist = false  #开启白名单模式，此时，用户123456 仅可使用下方列表中的存储
# 此时该用户只能使用名为 本机1 的存储
storages = ["本机1"]



# 其他配置

# [log]
# # 日志等级
# level = "DEBUG"

# [temp]
# # 下载文件临时目录, 请不要在此目录下存放任何其他文件
# base_path = "cache/"
# # 临时文件保存时间, 单位: 秒
# cache_ttl = 30

# [db]
# path = "data/data.db" # 数据库文件路径
```

### 🔍 日志

```shell
root@Ryan:~/saveany-bot# ./saveany-bot upgrade
Binary update failed: Get "https://api.github.com/repos/krau/SaveAny-Bot/releases": dial tcp 199.59.148.9:443: connect: connection refused
```
